"""Pure service-template platform detection and descriptor schema APIs."""

from .detect import (
    PLATFORM_DARWIN_LAUNCHD,
    PLATFORM_LINUX_OPENRC,
    PLATFORM_LINUX_SYSTEMD,
    PLATFORM_LINUX_SYSVINIT,
    PLATFORM_UNSUPPORTED,
    PLATFORM_WINDOWS_SERVICE,
    PLATFORM_WINDOWS_TASKSCHEDULER,
    SUPPORTED_PLATFORM_KEYS,
    UnsupportedServicePlatform,
    classify_platform,
    probe_host,
    require_windows_default,
    select_platform,
)
from .renderer import RenderResult, ServiceTemplateRenderError, render_service_template
from .schema import (
    STATUS_BLOCKED,
    STATUS_DEVELOPER_DEPLOYED,
    STATUS_PARTIAL,
    STATUS_TEMPLATE_READY,
    STATUS_UNSUPPORTED,
    CommandDescriptor,
    LogDescriptor,
    PortDescriptor,
    ServiceDescriptor,
    ServiceDescriptorError,
    normalize_descriptor,
)

__all__ = [
    "PLATFORM_DARWIN_LAUNCHD",
    "PLATFORM_LINUX_OPENRC",
    "PLATFORM_LINUX_SYSTEMD",
    "PLATFORM_LINUX_SYSVINIT",
    "PLATFORM_UNSUPPORTED",
    "PLATFORM_WINDOWS_SERVICE",
    "PLATFORM_WINDOWS_TASKSCHEDULER",
    "SUPPORTED_PLATFORM_KEYS",
    "UnsupportedServicePlatform",
    "classify_platform",
    "probe_host",
    "require_windows_default",
    "select_platform",
    "RenderResult",
    "ServiceTemplateRenderError",
    "render_service_template",
    "STATUS_BLOCKED",
    "STATUS_DEVELOPER_DEPLOYED",
    "STATUS_PARTIAL",
    "STATUS_TEMPLATE_READY",
    "STATUS_UNSUPPORTED",
    "CommandDescriptor",
    "LogDescriptor",
    "PortDescriptor",
    "ServiceDescriptor",
    "ServiceDescriptorError",
    "normalize_descriptor",
]
